Added default icon support for nullscape datapack
SNDST00M/material-dynmap pull request #123
Opened 2022-04-18 10:19 UTC by PssbleTrngle

## 🏗 Pull Request

- [x] Used a clear / meaningful title for this pull request.
- [x] Committed the changes and tested them in your userscript manager.
- [ ] Tested all entrypoints for cross-browser support (`src` folder).
- [x] Have read the **Contributing** part of the **README**.
- [ ] Passed `npm test`.
- [x] I noted my changes in the pull request body and/or changelog.

#### 👷🏾‍♀️ Fixes

- Map Icons for the custom `end_island` dimension added by the [Nullscape](https://www.planetminecraft.com/data-pack/nullscape/) datapack 

#### Description

Maps of the nullscape end island dimension use the overworld icons, instead of the end icons.

#### What changes have you made?

- some css rules have been adapted to include the `nullscape_end_island` maps.

#### What tests have you completed?

- [x] Tested this in Chrome .
- [ ] Tested this in Edge .
- [x] Tested this in Firefox .
- [ ] Tested this in Opera .
- [ ] Tested this in Electron .
- [ ] Tested this in Bukkit .

#### Anything else worth mentioning?

2022-04-18 11:22 UTC, SNDST00M requested changes

2022-04-18 11:22 UTC, SNDST00M commented on src/main.css
> +.dynmap .leaflet-control-container .leaflet-minimap-container[class*="nullscape_end_island"] .world .item .maptype,
Great! I'll note Nullscape support in the changelog, but a more generic solution would be good for the MC community here:
```suggestion
.dynmap .leaflet-control-container .leaflet-minimap-container:is([class^="end_"], [class*="_end_"]) .world .item .maptype,
```

2022-04-19 10:13 UTC, PssbleTrngle commented
I got a comment that someone requested a change but I'm not seeing anything here now and I'm slightly worrying if I'm going insane

2022-04-19 13:10 UTC, SNDST00M commented
I actually did suggest a more generic solution, but wanted to wait until tomorrow night when my laptop's repaired

I have however forgotten the selectors I was trying to target in the first place 😅

2022-04-19 20:13 UTC, SNDST00M commented
I think what you did is best :) will look at this and custom favicon support tomorrow

2022-04-20 17:40 UTC, PssbleTrngle commented
Some sort of custom icon support would be good too.
Even only using the default icons already provided for other dimensions (like using `the_end` icons for nullscape)

2022-06-09 19:44 UTC, merged